# Nginx'in çok küçük bir versiyonunu kullanıyoruz
FROM nginx:alpine

# Hazırladığımız index.html dosyasını Nginx'in yayın klasörüne kopyalıyoruz
COPY index.html /usr/share/nginx/html/index.html

# 80 portunu dışarı açıyoruz
EXPOSE 80
